blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/goostengine/goost-docs
    about: Report issues with documentation at the Goost Documentation repository.
  - name: Discussion
    url: https://github.com/goostengine/goost/discussions
    about: Discuss, share ideas, and ask questions for the Goost development.
  - name: Examples
    url: https://github.com/goostengine/goost-examples
    about: Request or propose usage examples at the Goost Examples repository.
  - name: Chat
    url: https://discord.gg/w6jBZnG
    about: Discuss and recieve development updates at the "Godot Extended Libraries" Discord server.
