name: 🤖 Android
on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'gd3'

env:
  GOOST_BASE_BRANCH: gd3
  SCONSFLAGS: godot_modules_enabled=no platform=android verbose=yes warnings=all werror=yes debug_symbols=no --jobs=4
  SCONS_CACHE_LIMIT: 8192

jobs:
  android-template:
    runs-on: "ubuntu-20.04"

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Load .scons_cache directory
        id: android-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk-bundle
        run: |
          scons target=release tools=no android_arch=armv7
          scons target=release tools=no android_arch=arm64v8
          cd godot/platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../../..
          ls -l godot/bin/
