name: 🐧 Linux
on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'gd3'

env:
  GOOST_BASE_BRANCH: gd3
  SCONSFLAGS: godot_modules_enabled=no verbose=yes warnings=all werror=yes debug_symbols=no --jobs=4
  SCONS_CACHE_LIMIT: 4096

jobs:
  mono-glue:
    runs-on: "ubuntu-20.04"
    name: Generate Mono Glue

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure dependencies
        run: |
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

      - name: Load .scons_cache directory
        id: linux-editor-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation (module_mono_enabled=yes mono_glue=no)
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=linuxbsd tools=yes target=release_debug module_mono_enabled=yes mono_glue=no copy_mono_root=yes

      - name: Generate Mono glue
        run: |
          pushd godot
          xvfb-run ./bin/godot.x11.opt.tools.64.goost.mono --generate-mono-glue modules/mono/glue || true
          popd

      - uses: actions/upload-artifact@v2
        with:
          name: mono-glue
          path: |
            godot/modules/mono/glue/**.gen.*
            godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/
            godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/

  linux-editor-mono:
    runs-on: "ubuntu-20.04"
    name: Linux Editor w/ Mono (target=release_debug, tools=yes)
    needs: mono-glue

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure dependencies
        run: |
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

      - name: Load .scons_cache directory
        id: linux-editor-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Download Glue
        uses: actions/download-artifact@v2
        with:
          name: mono-glue
          path: godot/modules/mono/glue

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=linuxbsd tools=yes target=release_debug module_mono_enabled=yes mono_glue=yes mono_static=yes copy_mono_root=yes

      - uses: actions/upload-artifact@v2
        with:
          name: godot.x11.opt.tools.64.goost.mono
          path: godot/bin/godot.x11.opt.tools.64.goost.mono

  linux-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      - name: Configure dependencies
        run: |
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

      - name: Load .scons_cache directory
        id: linux-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=linuxbsd target=release tools=no module_mono_enabled=yes mono_glue=no

  linux-server:
    runs-on: "ubuntu-20.04"
    name: Server (target=debug, tools=yes, tests=yes)

    steps:
      - uses: actions/checkout@v2

      - name: Configure dependencies
        run: |
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

      - name: Load .scons_cache directory
        id: linux-server-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation (goost_core_enabled=no)
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=server tools=yes target=debug debug_symbols=yes goost_core_enabled=no

      - name: Compilation (goost_editor_enabled=no)
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=server tools=yes target=debug debug_symbols=yes goost_editor_enabled=no

      - name: Compilation (goost_scene_enabled=no)
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=server tools=yes target=debug debug_symbols=yes goost_scene_enabled=no

      # Should be run last, must run all unit tests afterwards.
      - name: Compilation (goost_components_enabled=yes)
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=server tools=yes target=debug debug_symbols=yes goost_components_enabled=yes

      - name: Run unit tests
        run: |
          python run.py --windowed tests
